### ISSUE TITLE
Problem with Unity Package version number

### ISSUE THREAD

**Issue by runette** [nol1fe/delaunator-sharp#13]
Thanks for the package and the fix for the 2random" bug so fast - it only actually seemed to hit us when we upgraded to Unity 2020.2.

However - there is a problem with the release. You did not update the `package.json` version until after you made the 1.0.6 release.

we manage dependencies through UPM and only link to fixed releases. Currently - your 1.0.6 release looks to UPM like it is 1.0.5 and that fails because we already have 1.0.5.

Can you create a new release (I suggest 1.0.7) with the `package.json` version number updated (I suggest 1.0.7). That will bring everything back into line. 

Thanks and sorry for the trouble.

**Comment by favoyang** [comment]
I second the issue.

https://openupm.com/packages/com.nol1fe.delaunator/?subPage=pipelines

Your git tag is 1.0.6, but the package.json version is 1.0.5. Because you bump the version after creating the versioned Git tag.

To fix
- The easy way to go as @runette suggested is to bump to v1.0.7 and tag the new version.
- You can also re-tag v1.0.6. Refs https://dev.to/mheap/retag-a-git-tag-2iaf

**Comment by nol1fe** [comment]
Hello @runette, @favoyang 

Thanks for detailed issue description. I've pushed an update.

https://openupm.com/packages/com.nol1fe.delaunator/?subPage=pipelines

It seems like build passes right now

Cheers

**Comment by runette** [comment]
Worked thanks
