### ISSUE TITLE
UniformPoissonDiskSampler.SampleRectangle throws exception

### ISSUE THREAD

**Issue by circleapps** [nol1fe/delaunator-sharp#9]
I tried the **SampleRectangle**, then got overflow exception. Beside it, **SampleCirlce** works perfectly.

I am using  delaunator 1.0.5 with Unity 2020.1. Thanks.

Below is my code:

var sampler = UniformPoissonDiskSampler.SampleRectangle(new Vector2(-10, 10), new Vector2(10, -10),  2);

``
OverflowException
DelaunatorSharp.Unity.UniformPoissonDiskSampler.Sample (UnityEngine.Vector2 topLeft, UnityEngine.Vector2 lowerRight, System.Nullable`1[T] rejectionDistance, System.Single minimumDistance, System.Int32 pointsPerIteration) (at Library/PackageCache/com.nol1fe.delaunator@d542c6bf57/Runtime/Scripts/UniformPoissionDiskSampler.cs:72)
DelaunatorSharp.Unity.UniformPoissonDiskSampler.SampleRectangle (UnityEngine.Vector2 topLeft, UnityEngine.Vector2 lowerRight, System.Single minimumDistance, System.Int32 pointsPerIteration) (at Library/PackageCache/com.nol1fe.delaunator@d542c6bf57/Runtime/Scripts/UniformPoissionDiskSampler.cs:54)
DelaunatorSharp.Unity.UniformPoissonDiskSampler.SampleRectangle (UnityEngine.Vector2 topLeft, UnityEngine.Vector2 lowerRight, System.Single minimumDistance) (at Library/PackageCache/com.nol1fe.delaunator@d542c6bf57/Runtime/Scripts/UniformPoissionDiskSampler.cs:50)
``

**Comment by nol1fe** [comment]
Hello @circleapps 
UniformPoissonDiskSampler is not a part of Delaunator. However i took a look at it and it seems that constructor parameter names are very misleading. 

Instead of 
`SampleRectangle(Vector2 topLeft, Vector2 lowerRight) `
Try
`SampleRectangle(Vector2 bottomLeft, Vector2 topRight)`

In your case it will be
`var sampler = UniformPoissonDiskSampler.SampleRectangle(new Vector2(-10, -10), new Vector2(10, 10), 2);`

But still In that case generated output will look like this.

![image](https://user-images.githubusercontent.com/23663977/101279962-70c5de00-37c6-11eb-9cdb-0ac4986428b6.png)


If you need perfect rectangle, you have to add to list all of the corners

```
var sampler = UniformPoissonDiskSampler.SampleRectangle(new Vector2(-10, -10), new Vector2(10, 10), 2);
points = sampler.Select(point => new Vector2(point.x, point.y)).ToPoints().ToList();

points.Add(new Point(-10, -10));
points.Add(new Point(10, -10));
points.Add(new Point(10, 10));
points.Add(new Point(- 10, 10));
```
![image](https://user-images.githubusercontent.com/23663977/101279949-53910f80-37c6-11eb-8165-8f72c86a1411.png)

Cheers

**Comment by circleapps** [comment]
Thanks! It works for me.
